version: '3.1'
services:
  app:
    image: app-springboot
    container_name: app-springboot
    build: ./
    ports:
      - 8080:8080
    depends_on:
      - dbpostgresql
    links:
      - dbpostgresql

  dbpostgresql:
    image: postgres
    volumes:
      - postgres1-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=localdb
    restart: unless-stopped


volumes:
  postgres1-data: