spring:
  profiles:
    active: dev


logging:
  file:
    path: .

---
spring:
  profiles: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          time_zone: '-05:00'




server:
  port: 5000

